### ISSUE TITLE
username

### ISSUE THREAD

**Issue by bash0x0** [bash/bash#1]
Hi

How much for you to change username, so i can get /bash instead of my current?

Please answer ASAP when you see this :)

**Comment by tautropfli** [comment]
Even if I wanted to change my username, selling it to you would be against the [GitHub Username Policy](https://docs.github.com/en/site-policy/other-site-policies/github-username-policy):
> Attempts to sell, buy, or solicit other forms of payment in exchange for account names are prohibited and may result in permanent account suspension.

**Comment by bash0x0** [comment]
Oh yeah, i totally forgot that? my mistake. Sorry

Have a great day

**Comment by janhohenheim** [comment]
I will buy it for three Schmeckles and one Flurbo
